version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: .
    container_name: queue_api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  worker:
    build: .
    command: python worker/consumer.py
    depends_on:
      - rabbitmq